name: Actions and Usage of Checkout Action

on:
  push

jobs:
    actions_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v6
        
        - name: Check the files from repo
          run: ls
        
        - name: Read file from repo
          run: cat README.md
