name: Execute shell script

on:
  push:
    branches:
      - main

jobs:
    actions_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v6
        
        - name: List Repository
          run: ls -ltra

        - name: Permission to Shell Script
          run: chmod +x ./ascii-script.sh

        - name: Execute Shell Script
          run: sh ./ascii-script.sh
        
    
