name: Wokrflows With Multiple Jobs 

on:
  push:
    branches:
      - main

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Running job 1
          run: echo "Hello from job 1"

    build_job_2:
        runs-on: ubuntu-latest
        steps:
            - name: Running Job 2
              run: echo "Hello from job 2"
    
    build_job_3:
        runs-on: ubuntu-latest
        steps:
            - name: Running Job 3
              run: echo "Hello from Job 3"
        
    
