name: Running Multi-Line Command

on:
  push

jobs:
    actions_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v6
        
        - name: Check the files from repo
          run: |
            echo "Running Multi-Line Commands Workflow"
            ls -la
            sleep 10s
            echo "Read file from repository"
            cat README.md
