name: Executing a Third-Party CLI

on:
  push

jobs:
    actions_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v6
        
        - name: Install Cosway
          run: sudo apt-get update && sudo apt-get install -y cowsay

        - name: Generate ASCII Artwork
          run: |
            cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
            cat dragon.txt
        
        - name: List Repository Files
          run: ls -ltra
        
    
